// import novieta1 from "../../../public/project/novieta1.png";
// import novieta2 from "../../../public/project/novieta2.png";
// import novieta3 from "../../../public/project/novieta3.png";
// import novieta4 from "../../../public/project/novieta4.png";

export const allProjects = [
  {
    id: 13,
    title: "Akoya Deluxe Cleaning",
    description:
      "User-friendly, modern design showcasing top resources for managing overtime.",
    featured: "/project/lundary1.PNG",
    thumbnails: [
      "/project/lundary1.PNG",
      "/project/lundary2.PNG",
      "/project/lundary3.PNG",
      "/project/lundary4.PNG",
    ],
    link: "https://lundary.vercel.app",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 14,
    title: "Qatar Charity",
    description: "A digital platform connecting donors with RACA-approved charities in Qatar, offering complete transparency and real-time tracking.",
    featured: "/project/charity.png",
    thumbnails: [
      "/project/charity1.png",
      "/project/charity2.png",
      "/project/charity3.png",
      "/project/charity4.png",
    ],
    link: "https://charity-blush-psi.vercel.app",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 15,
    title: "City Zoo – Explore Wildlife & Conservation",
    description: "City Zoo offers an immersive wildlife experience, combining education, conservation, and family-friendly adventures across 180 acres of exotic habitats.",
    featured: "/project/zoo3.png",
    thumbnails: [
      "/project/zoo1.png",
      "/project/zoo2.png",
      "/project/zoo.png",
      "/project/zoo4.png",
    ],
    link: "https://zoo-drab.vercel.app/",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 16,
    title: "Al-Khaldi Law Firm – Strategic Legal Excellence in the GCC",
    description: "Al-Khaldi Law Firm delivers strategic legal excellence across the GCC, offering trusted, professional, and innovative legal solutions for individuals, corporations, and government clients.",
    featured: "/project/lawyer.png",
    thumbnails: [
      "/project/lawyer1.png",
      "/project/lawyer2.png",
      "/project/lawyer3.png",
      "/project/lawyer4.png",
    ],
    link: "https://lawyer-pi-three.vercel.app",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 17,
    title: "Scientific Quality Systems – Professional Pest Control in Qatar",
    description: "Providing fast, safe, and certified pest control solutions across Qatar, specializing in cockroaches, rodents, bed bugs, mosquitoes, and eco-friendly treatments with 24/7 service.",
    featured: "/project/pest.png",
    thumbnails: [
      "/project/pest1.png",
      "/project/pest2.png",
      "/project/pest3.png",
      "/project/pest4.png",
    ],
    link: "https://pest-control-omega.vercel.app/",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 18,
    title: "Business Solutions Across GCC",
    description: "Across GCC empowers startups and entrepreneurs with strategic support, resources, and guidance to launch, scale, and succeed across the Gulf Cooperation Council region.",
    featured: "/project/gcc.png",
    thumbnails: [
      "/project/gcc1.png",
      "/project/gcc2.png",
      "/project/gcc3.png",
      "/project/gcc4.png",
    ],
    link: "https://business-startup-six.vercel.app/",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 1,
    title: "Multi-Service Creative Agency",
    description:
      "A fully responsive online store with cart, payment gateway, and admin panel.",
    featured: "/project/novieta1.png",
    thumbnails: [
      "/project/novieta1.png",
      "/project/novieta2.png",
      "/project/novieta3.png",
      "/project/novieta4.png",
    ],
    link: "https://novietaaplus.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 2,
    title: "Trend Car Care",
    description:
      "A fully responsive online store with cart, payment gateway, and admin panel.",
    featured: "/project/trend1.png",
    thumbnails: [
      "/project/trend1.png",
      "/project/trend2.png",
      "/project/trend3.png",
      "/project/trend4.png",
    ],
    link: "https://trendcarcare.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 3,
    title: "The Givers Consulting",
    description:
      "A versatile and forward-thinking company offering a comprehensive suite of services.",
    featured: "/project/thegiverconsulting1.PNG",
    thumbnails: [
      "/project/thegiverconsulting1.PNG",
      "/project/thegiverconsulting2.PNG",
      "/project/thegiverconsulting3.PNG",
      "/project/thegiverconsulting4.PNG",
    ],
    link: "https://thegiversconsulting.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 4,
    title: "Cash rewards game",
    description:
      "Become part of a thriving global community today and unlock thousands of dollars in earnings.",
    featured: "/project/bmx1.png",
    thumbnails: [
      "/project/bmx1.png",
      "/project/bmx2.png",
      "/project/bmx3.png",
      "/project/bmx4.png",
    ],
    link: "https://bmx-frontend.vercel.app",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 5,
    title: "Innovative Workforce Management Solutions",
    description:
      "Innovative Workforce Management Solutions streamline employee scheduling, attendance tracking, and productivity monitoring using advanced technologies. ",
    featured: "/project/glidesk1.PNG",
    thumbnails: [
      "/project/glidesk1.PNG",
      "/project/glidesk2.PNG",
      "/project/glidesk3.PNG",
      "/project/glidesk4.PNG",
    ],
    link: "https://glidesk.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 6,
    title: "Softech Business Solutions",
    description:
      "Softech Business Solutions is a forward-thinking company specializing in delivering innovative software and technology services to businesses of all sizes.",
    featured: "/project/softech1.PNG",
    thumbnails: [
      "/project/softech1.PNG",
      "/project/softech2.PNG",
      "/project/softech3.PNG",
      "/project/softech4.PNG",
    ],
    link: "https://www.softechbusinessservices.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  },
  {
    id: 7,
    title: "Nasa Teck Innovations It Services",
    description:
      "NASA Teck Innovations IT Services is a technology company based in Bahawalpur, Pakistan, operating under the name Sky Innovations IT Services L.L.C.",
    featured: "/project/nasateck1.PNG",
    thumbnails: [
      "/project/nasateck1.PNG",
      "/project/nasateck2.PNG",
      "/project/nasateck3.PNG",
      "/project/nasateck4.PNG",
    ],
    link: "https://nasateck.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website development",
  }
];
